### ISSUE TITLE
Einrichtung E-Mail-Adresse für Christian Uehlenbruck (Trainer U6)

### ISSUE THREAD

**Issue by benbue** [benbue/esv-olympia-koeln#7]
Bitte nach Einrichtung eine Info an Christian.Uehlenbruck@vodafone.com und Maik Münzinger

**Comment by kurt-c-hose** [comment]
Hi Ben,
ich kann das gern übernehmen, benötige aber dafür einen Zugang?
LG Guido @benbue

**Comment by benbue** [comment]
Hi Guido,
habe Deinen Kommentar jetzt erst gesehen. Die Zugangsdaten sind auf dem Weg zu Dir!
LG Ben

**Comment by kurt-c-hose** [comment]
done :)

**Comment by benbue** [comment]
merci - auch hier: bin nicht sicher, ob's eine Weiterleitung oder ein "komplettes" Postfach sein sollte für Christian. Im Zweifel wird er sich melden.

**Comment by kurt-c-hose** [comment]
christian hat ein Postfach UND die Weiterleitung
