### ISSUE TITLE
Einrichtung E-Mail-Adresse für Norbert Leisten <norbert.leisten@web.de> (kein Trainer, aber Mitarbeiter)

### ISSUE THREAD

**Issue by benbue** [benbue/esv-olympia-koeln#9]
norbert.leisten@esv-olympia.koeln  (private Adresse ist <norbert.leisten@web.de>, kein Trainer, aber Mitarbeiter)

**Comment by kurt-c-hose** [comment]
Ich habe eine Weiterleiterleitung auf die private Mail eingerichtet und eine Info- und Testmail an beide gesendet

**Comment by benbue** [comment]
Vielen Dank - ich bin nicht sicher, ob Norbert evtl. ein komplettes E-Mail-Postfach nutzen wollte, aber das wird er im Zweifel schon sagen  ;-)

**Comment by kurt-c-hose** [comment]
hat sich bisher nicht rückgemeldet ...
